### ISSUE TITLE
Too many or few errors?

### ISSUE THREAD

**Issue by Deepesh9620** [karaketir16/file2video#2]
![Screenshot_20240611-193538_Parsec](https://github.com/karaketir16/file2video/assets/161910288/ddb69a2d-1897-4af6-80e1-f668ff287e1f)
Can you please help me resolve this

**Comment by karaketir16** [comment]
Did you run with default parameters, I mean did you changed anything in code?

Did you upload the video to youtube and download, or just encode and decode?

**Comment by Deepesh9620** [comment]
I didn't change any code. 
I encoded the file, uploaded it to youtube waited for the processing and pasted the link in the command.

**Comment by karaketir16** [comment]
You can try downloading the video with another tool (there are many tools for downloading videos from YouTube).

Then, try decoding the downloaded video. I am not sure if this will make any difference.

It is likely that YouTube's video compression creates more errors than Reed-Solomon can fix.

If you lose any data, sorry for that. I didn't expect that to happen. I should add a warning to the readme.

The best I can do is add an option for creating a file even if errors exist. This will create the corrupted file, and maybe you can recover some data from it.

If you have the original generated video file, can you try to decode it without uploading it to YouTube?

**Comment by Deepesh9620** [comment]
No data was lost I didn't delete the original file was just testing of this script. Thanks

**Comment by karaketir16** [comment]
Thanks for reporting. I added a warning to README. 

If you want to try, you can increase the `global_reedEC` value in `common.py` that should be reduce the risk of corruption. Same values must be used for encoding and decoding.
